---
abstract: 'Expansion of test functionalities that appear to be frequently used while testing.'
author:
  - 'Jurij Fajnberg <fajnbergj@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Simple: '0'
dynamic_config: 0
generated_by: 'JSF'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Expander
no_index:
  directory:
    - t
provides:
  Test::Expander:
    file: lib/Test/Expander.pm
    version: '2.4.0'
  Test::Expander::Constants:
    file: lib/Test/Expander/Constants.pm
    version: '2.4.0'
requires:
  B: '0'
  Const::Fast: '0'
  Exporter: '0'
  File::chdir: '0'
  File::Temp: '0'
  Getopt::Long: '0'
  Importer: '0'
  PadWalker: '0'
  Path::Tiny: '0.144'
  Scalar::Readonly: '0'
  Term::ANSIColor: '0'
  Test::Builder: '0'
  Test2::API: '0'
  Test2::Tools::Basic: '0'
  Test2::Tools::Explain: '0'
  Test2::Tools::Subtest: '0'
  Test2::V0: '0'
  perl: '5.008009'
resources:
  bugtracker: https://github.com/jsf116/Test-Expander
  repository: git://github.com/jsf116/Test-Expander.git
version: '2.4.0'
